
// Generated by build tool, do not edit
using System;
using System.Reflection;
[assembly: AssemblyCopyright("Copyright © 2021 Topten Software. All Rights Reserved")]
[assembly: AssemblyVersion("0.1.100")]
[assembly: AssemblyFileVersion("0.1.100")]
[assembly: AssemblyCompany("Topten Software")]
[assembly: AssemblyProduct("ThemeKit")]

static class BuildInfo
{
	public static DateTime Date = new DateTime(2021, 8, 20, 13, 4, 38, DateTimeKind.Utc);
}
	